---
development:
  dialect: postgres
  database: postgres
  user: postgres
  password: {{env "DEV_DB_PASSWORD"}}
  host: {{env "DEV_DB_HOST"}}
  pool: 5

test:
  dialect: postgres
  database: postgres
  user: postgres
  password: {{env "TEST_DB_PASSWORD"}}
  host: {{env "TEST_DB_HOST"}}
  pool: 5

production:
  dialect: postgres
  database: postgres
  user: postgres
  password: {{env "PRD_DB_PASSWORD"}}
  host: {{env "PRD_DB_HOST"}}
  pool: 5
